### ISSUE TITLE
Issue sending OTP to customer

### ISSUE THREAD

**Issue by poojan007** [playsms/plugin-otp#1]
I was able to successfully trigger the otp webservice from my application and it also reaches the playsms. But i dont receive any message following is the issue thrown.

127.0.0.1 localhost 2017-03-27 16:16:07 PID58d8e6670ca8a - L2 otp_hook_webservices_output # OTP start sending u:admin msisdn:+97517457592 template:Your verification code is {OTP}
127.0.0.1 localhost 2017-03-27 16:16:07 PID58d8e6670ca8a - L2 sendsms # start uid: sender_id:[] smsc:[]
127.0.0.1 localhost 2017-03-27 16:16:07 PID58d8e6670ca8a - L2 sendsms_queue_create # saving queue_code:92f61c8bc1ef9075701ca64923075548 src: scheduled:2017-03-27 16:16:07
127.0.0.1 localhost 2017-03-27 16:16:07 PID58d8e6670ca8a - L2 sendsms # fail to finalize queue creation, exit immediately
127.0.0.1 localhost 2017-03-27 16:16:07 PID58d8e6670ca8a - L2 otp_hook_webservices_output # OTP status:ERR error:200 otp: u:admin msisdn: smslog_id:

**Comment by dpenezic** [comment]
Hi, 
I have same issue, but finally found reason (missing parameter in function).

**Comment by antonraharja** [comment]
please test, thanks

**Comment by dpenezic** [comment]
Hi @antonraharja ,
I just test code with last version of playSMS 1.4.2 on RPi and now plugin work correctly
